Adding Shank Accounts (#63)

diff --git a/scripts/shank b/scripts/shank
--- a/scripts/shank
+++ b/scripts/shank
@@ -18,5 +18,52 @@ source ${CONFIG}
 shank idl --crate-root "${PROJECT_ROOT}/restaking_sdk" -p ${RESTAKING_PROGRAM_ID} -o "${IDL_DIR}"
 shank idl --crate-root "${PROJECT_ROOT}/vault_sdk" -p ${VAULT_PROGRAM_ID} -o "${IDL_DIR}"
 
+shank idl --crate-root "${PROJECT_ROOT}/vault_core" -p ${VAULT_PROGRAM_ID} -o "${IDL_DIR}"
+shank idl --crate-root "${PROJECT_ROOT}/restaking_core" -p ${VAULT_PROGRAM_ID} -o "${IDL_DIR}"
+
+shank idl --crate-root "${PROJECT_ROOT}/core" -p ${VAULT_PROGRAM_ID} -o "${IDL_DIR}"
+
+# Merge the idl files
+echo "Adding accounts and appending core types to SDK files..."
+
+# Check if jq is installed
+if ! command -v jq &> /dev/null; then
+    echo "Error: jq is not installed. Please install it to run this script."
+    exit 1
+fi
+
+# Define the input files
+CORE_FILE="${IDL_DIR}/jito_jsm_core.json"
+VAULT_CORE_FILE="${IDL_DIR}/jito_vault_core.json"
+VAULT_SDK_FILE="${IDL_DIR}/jito_vault_sdk.json"
+RESTAKING_CORE_FILE="${IDL_DIR}/jito_restaking_core.json"
+RESTAKING_SDK_FILE="${IDL_DIR}/jito_restaking_sdk.json"
+
+# Extract the "accounts" and "types" arrays from the files
+CORE_TYPES=$(jq '.types' "$CORE_FILE")
+VAULT_ACCOUNTS=$(jq '.accounts' "$VAULT_CORE_FILE")
+VAULT_TYPES=$(jq '.types' "$VAULT_CORE_FILE")
+RESTAKING_ACCOUNTS=$(jq '.accounts' "$RESTAKING_CORE_FILE")
+
+# Add accounts and append CORE_TYPES to the "types" array in the SDK files
+jq --argjson vault_accounts "$VAULT_ACCOUNTS" --argjson vault_types "$VAULT_TYPES" --argjson core_types "$CORE_TYPES" '
+    .accounts = ($vault_accounts) |
+    .types += ($core_types + $vault_types)
+' "$VAULT_SDK_FILE" > "${VAULT_SDK_FILE}.tmp"
+
+jq --argjson restaking_accounts "$RESTAKING_ACCOUNTS" --argjson core_types "$CORE_TYPES" '
+    .accounts = ($restaking_accounts) |
+    .types += $core_types
+' "$RESTAKING_SDK_FILE" > "${RESTAKING_SDK_FILE}.tmp"
+
+# Replace the original sdk files with the updated ones
+mv "${VAULT_SDK_FILE}.tmp" "$VAULT_SDK_FILE"
+rm "${VAULT_CORE_FILE}"
+
+mv "${RESTAKING_SDK_FILE}.tmp" "$RESTAKING_SDK_FILE"
+rm "${RESTAKING_CORE_FILE}"
+
+rm "${CORE_FILE}"
+
 echo "------------------------"
 echo "All configurations processed."
